<robot name="Car" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- camera part -->
    <xacro:property name="camera_length" value="0.02"/>
    <xacro:property name="camera_width" value="0.05"/>
    <xacro:property name="camera_height" value="0.05"/>
    <xacro:property name="camera_mass" value="0.01"/>
    <xacro:property name="camera_joint_x" value="0.08"/>
    <xacro:property name="camera_joint_y" value="0"/>
    <xacro:property name="camera_joint_z" value="${base_link_length/2 + camera_height/2}"/>
    <xacro:include filename="intertia_matrix.xacro"/>
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <material name="camera_color">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
             <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_height}"/>
    </link>
    <joint name="camera2base_link" type="fixed">
        <parent link="base_link"/>
        <child link="camera"/>
        <origin xyz="${camera_joint_x} ${camera_joint_y} ${camera_joint_z}" rpy="0 0 0"/>
    </joint>

    <!-- gazebo color set -->
    <gazebo reference="camera">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>