<robot name="Car" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- laser part -->
    <!-- support -->
    <xacro:property name="support_radius" value="0.01"/>
    <xacro:property name="support_length" value="0.15"/>
    <xacro:property name="support_mass" value="0.1"/>
    <!-- laser  -->
    <xacro:property name="laser_radius" value="0.03"/>
    <xacro:property name="laser_length" value="0.05"/>
    <xacro:property name="laser_mass" value="0.15"/>
    <!-- xyz rpy -->
    <xacro:property name="support_joint_x" value="0"/>
    <xacro:property name="support_joint_y" value="0"/>
    <xacro:property name="support_joint_z" value="${base_link_length/2 + support_length/2}"/>
    <xacro:property name="laser_joint_x" value="0"/>
    <xacro:property name="laser_joint_y" value="0"/>
    <xacro:property name="laser_joint_z" value="${support_length/2 + laser_length/2}"/>
    <xacro:include filename="intertia_matrix.xacro"/>
    <link name="support">
        <visual>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}"/>
            </geometry>
            <material name="support_color">
                <color rgba="0 0 1 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${support_mass}" r="${support_radius}" h="${support_length}"/>
    </link>

    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}"/>
            </geometry>
            <material name="laser_color">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${laser_mass}" r="${laser_radius}" h="${laser_length}"/>
    </link>

    <joint name="support2base_link" type="fixed">
        <parent link="base_link"/>
        <child link="support"/>
        <origin xyz="${support_joint_x} ${support_joint_y} ${support_joint_z}" rpy="0 0 0"/>
    </joint>

    <joint name="laser2support" type="fixed">
        <parent link="support"/>
        <child link="laser"/>
        <origin xyz="${laser_joint_x} ${laser_joint_y} ${laser_joint_z}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="laser">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="support">
        <material>Gazebo/Gray</material>
    </gazebo>
</robot>